# This is a basic workflow to help you get started with Actions

name: BuildDebianClient

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master-new branch
  push:
    branches: [ main ]
    tags: 
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
            submodules: recursive

      # Update apt sources
      - name: Update apt sources
        run: sudo apt-get update
      
      # Install pre-reuisites
      - name: Install Prerequisites
        run: sudo apt-get install git-core gcc g++ make cmake qtbase5-dev qtbase5-dev-tools qt5-qmake qtchooser qttools5-dev-tools dh-make build-essential pbuilder

      # Runs a single command using the runners shell
      - name: Build
        run: ./build_debian.sh


      # Runs a single command using the runners shell
      - name: List files
        run: ls -la

      
      #Upload the ROM
      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: Debian Package
          path: apolloexplorer*.deb
        
